name: Publisher

on:
  workflow_run:
    workflows: ["Testing"]
    types:
      - completed
  push:
    branches: [ net8 ]
  pull_request:
    branches: [ net8 ]
    
jobs:
  # Set the job key. The key is displayed as the job name
  # when a job name is not provided
  publish:     
    runs-on: ubuntu-latest
    permissions:
        packages: write
    steps:
    # Checks out a copy of your repository on the ubuntu-latest machine
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'
        
    - name: Install dependencies
      run: |
          dotnet restore src/Dapper.FSharp/Dapper.FSharp.fsproj
          dotnet restore src/Dapper.FSharp.MySQL/Dapper.FSharp.MySQL.fsproj
          dotnet restore src/Dapper.FSharp.SQLite/Dapper.FSharp.SQLite.fsproj
      
    - name: Build
      run: |
          dotnet build src/Dapper.FSharp/Dapper.FSharp.fsproj --configuration Release --no-restore
          dotnet build src/Dapper.FSharp.MySQL/Dapper.FSharp.MySQL.fsproj --configuration Release --no-restore
          dotnet build src/Dapper.FSharp.SQLite/Dapper.FSharp.SQLite.fsproj --configuration Release --no-restore

    - name: Pack
      run: |
        dotnet pack --configuration Release src/Dapper.FSharp/Dapper.FSharp.fsproj --output .
        dotnet pack --configuration Release src/Dapper.FSharp.MySQL/Dapper.FSharp.MySQL.fsproj --output .
        dotnet pack --configuration Release src/Dapper.FSharp.SQLite/Dapper.FSharp.SQLite.fsproj --output .
      
    - name: Prep packages
      run: dotnet nuget add source --username p1eXu5 --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/p1eXu5/index.json"

    - name: Publish to GitHub packages
      run: |
        dotnet nuget push Dapper.FSharp.4*.nupkg --api-key ${{ secrets.GITHUB_TOKEN }} --source "github" --skip-duplicate
        dotnet nuget push Dapper.FSharp.MySQL.4*.nupkg --api-key ${{ secrets.GITHUB_TOKEN }} --source "github" --skip-duplicate
        dotnet nuget push Dapper.FSharp.SQLite.4*.nupkg --api-key ${{ secrets.GITHUB_TOKEN }} --source "github" --skip-duplicate
